language: objective-c

notifications:
  email: false

env:
 matrix:
  - alpha
  - beta
  - latest
  - MONO_VERSION="4.2.1"

before_install:
 - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
 - brew update
 - brew install libuv --universal

script:
 - bundle install
 - bundle exec rake
