version: 1.0.{build}

environment:
  matrix:
   - arch: "x86"
     MSBUILD_PLATFORM: x86
   - arch: "x64"
     MSBUILD_PLATFORM: "Any CPU"
   - arch: "x64"
     MSBUILD_PLATFORM: "Any CPU"
     USE_DOTNET_CLI: 1

install:
 - ps: Start-FileDownload 'https://github.com/libuv/libuv/archive/v1.7.5.zip'
 - cmd: 7z x v1.7.5.zip & cd libuv-1.7.5 & vcbuild.bat %arch% shared debug
 - cmd: mkdir src\Suave.Tests\bin\Release\ & cp libuv-1.7.5\Debug\libuv.dll src\Suave.Tests\bin\Release\libuv.dll
 
build_script:
 - cmd: gem sources -r https://rubygems.org/
 - cmd: gem install bundler --no-ri --no-rdoc --source http://rubygems.org/
 - cmd: bundle install
 - cmd: bundle exec rake appveyor
 # dotnet cli
 # - create Suave coreclr nugets packages
 - cmd: if "%USE_DOTNET_CLI%" == "1" bundle exec rake dotnetcli:do_netcorepackage
 # - merge standard and dotnetcli nupkgs
 - cmd: if "%USE_DOTNET_CLI%" == "1" bundle exec rake dotnetcli:merge
 
artifacts:
 - path: build\pkg\*.nupkg 

test:  off

nuget:
  project_feed: true


