steps:
- id: suaveio-docs-builder
  name: eu.gcr.io/cloud-builders/docker:latest
  args: ['build', '--rm=false', '-t', 'eu.gcr.io/$PROJECT_ID/suaveio-docs-builder', '-f', 'Dockerfile.builder', '.']
- id: suaveio-docs-build
  name: eu.gcr.io/$PROJECT_ID/suaveio-docs-builder
  entrypoint: docker
  args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/suaveio-docs", "."]
  waitFor: ["suaveio-docs-builder"]
- id: suaveio-docs-push
  name: eu.gcr.io/$PROJECT_ID/suaveio-docs-builder
  entrypoint: docker
  args: ["push", "eu.gcr.io/$PROJECT_ID/suaveio-docs"]
  waitFor: ["suaveio-docs-build"]
- id: suaveio-docs-push
  name: eu.gcr.io/$PROJECT_ID/suaveio-docs-builder
  entrypoint: bash
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials $PROJECT_ID --zone europe-west1
    kubectl set image deployment/suaveio-docs suaveio-docs=eu.gcr.io/$PROJECT_ID/suaveio-docs